import { Layer } from 'effect';

import {
  createPullRequestComment,
  createPullRequestReview,
  deletePullRequestComment,
  deletePullRequestReview,
  findUserCommits,
  findUserIssues,
  findUserPullRequests,
  getIssue,
  getIssueComments,
  getOrgRepositories,
  getPullRequest,
  getPullRequestComments,
  getPullRequestReviewComments,
  getPullRequestReviews,
  getRepoIssues,
  getRepoLanguages,
  getRepoPullRequests,
  getRepoPullRequestsComments,
  getRepoReleases,
  getRepoTags,
  getUserEvents,
  getUserOrgs,
  getUserProfile,
  getUserRepositories,
} from '@implementation';

import { OctokitLayerContext } from './octokit.context.js';

export const OctokitLayerLive = Layer.succeed(
  OctokitLayerContext,
  OctokitLayerContext.of({
    getUserProfile,
    getUserOrgs,
    getUserEvents,
    findUserCommits,
    findUserIssues,
    findUserPullRequests,
    getOrgRepositories,
    getUserRepositories,
    getRepoPullRequests,
    getRepoPullRequestsComments,
    getRepoIssues,
    getRepoLanguages,
    getRepoTags,
    getRepoReleases,
    getIssue,
    getIssueComments,
    getPullRequest,
    getPullRequestReviews,
    getPullRequestComments,
    getPullRequestReviewComments,
    createPullRequestComment,
    createPullRequestReview,
    deletePullRequestReview,
    deletePullRequestComment,
  }),
);
