import { Layer } from 'effect';

import {
  createPullRequestComment,
  createPullRequestReview,
  deletePullRequestComment,
  deletePullRequestReview,
  getIssue,
  getIssueComments,
  getOrgRepositories,
  getPullRequest,
  getPullRequestComments,
  getPullRequestReviewComments,
  getPullRequestReviews,
  getRepoDetails,
  getRepoIssues,
  getRepoLanguages,
  getRepoPullRequests,
  getRepoPullRequestsComments,
  getRepoReleases,
  getRepoTags,
  getUserCommitsCount,
  getUserEvents,
  getUserIssuesCount,
  getUserOrgs,
  getUserProfile,
  getUserPullRequestsCount,
  getUserRepositories,
  searchUserCommits,
  searchUserIssues,
  searchUserPullRequests,
} from '@implementation';

import { OctokitLayerContext } from './octokit.context.js';

export const OctokitLayerLive = Layer.succeed(
  OctokitLayerContext,
  OctokitLayerContext.of({
    getUserProfile,
    getUserOrgs,
    getUserEvents,
    searchUserCommits,
    searchUserIssues,
    searchUserPullRequests,
    getUserCommitsCount,
    getUserIssuesCount,
    getUserPullRequestsCount,
    getOrgRepositories,
    getUserRepositories,
    getRepoPullRequests,
    getRepoPullRequestsComments,
    getRepoIssues,
    getRepoLanguages,
    getRepoTags,
    getRepoReleases,
    getIssue,
    getIssueComments,
    getPullRequest,
    getPullRequestReviews,
    getPullRequestComments,
    getPullRequestReviewComments,
    createPullRequestComment,
    createPullRequestReview,
    deletePullRequestReview,
    deletePullRequestComment,
    getRepoDetails,
  }),
);
