name: ⚡ Coverage badges generation

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage-badges-generation:
    name: 📣 Coverage badges generation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: 📦 Setup bun
        uses: oven-sh/setup-bun@b7a1c7ccf290d58743029c4f6903da283811b979 # v2.1.0

      - name: ⎔ Setup node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: ".node-version"
          registry-url: "https://registry.npmjs.org"
          cache-dependency-path: ./package.json

      - name: 📥 Install deps
        run: bun install --frozen-lockfile

      - name: 🔍 Tests
        run: bun run test-ci

      - name: 🥁 Generating coverage badges
        uses: jpb06/coverage-badges-action@a3fa2847615db8b69437e885621aa734bfa94e9b # v1.4.6
        with:
          badges-icon: vitest
          badges-labels-prefix: "Vitest coverage"
          commit-message: "chore: updating coverage badges"
          commit-user: jpb06
          commit-user-email: jpb.06@outlook.com
